using Microsoft.Extensions.Logging;
using MusicUniverse.Application.Common.Interfaces;
using MusicUniverse.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace MusicUniverse.Application.System.Seed
{
    public class DbSeedService : IDbSeedService
    {
        private readonly IMusicUniverseDbContext _dbContext;

        private readonly ILogger<DbSeedService> _log;

        public DbSeedService(IMusicUniverseDbContext dbContext, ILogger<DbSeedService> log)
        {
            _dbContext = dbContext;
            _log = log;
        }

        public async Task SeedAsync(CancellationToken cancellationToken)
        {
            _log.LogInformation("Seeding...");

            _dbContext.Countries.AddRange(new[]
            {
                new Country() { Code = "AF", Name = "Afghanistan"},
new Country() { Code = "AX", Name = "Åland Islands"},
new Country() { Code = "AL", Name = "Albania"},
new Country() { Code = "DZ", Name = "Algeria"},
new Country() { Code = "AS", Name = "American Samoa"},
new Country() { Code = "AD", Name = "Andorra"},
new Country() { Code = "AO", Name = "Angola"},
new Country() { Code = "AI", Name = "Anguilla"},
new Country() { Code = "AQ", Name = "Antarctica"},
new Country() { Code = "AG", Name = "Antigua and Barbuda"},
new Country() { Code = "AR", Name = "Argentina"},
new Country() { Code = "AM", Name = "Armenia"},
new Country() { Code = "AW", Name = "Aruba"},
new Country() { Code = "AU", Name = "Australia"},
new Country() { Code = "AT", Name = "Austria"},
new Country() { Code = "AZ", Name = "Azerbaijan"},
new Country() { Code = "BS", Name = "Bahamas"},
new Country() { Code = "BH", Name = "Bahrain"},
new Country() { Code = "BD", Name = "Bangladesh"},
new Country() { Code = "BB", Name = "Barbados"},
new Country() { Code = "BY", Name = "Belarus"},
new Country() { Code = "BE", Name = "Belgium"},
new Country() { Code = "BZ", Name = "Belize"},
new Country() { Code = "BJ", Name = "Benin"},
new Country() { Code = "BM", Name = "Bermuda"},
new Country() { Code = "BT", Name = "Bhutan"},
new Country() { Code = "BO", Name = "Bolivia, Plurinational State of"},
new Country() { Code = "BQ", Name = "Bonaire, Sint Eustatius and Saba"},
new Country() { Code = "BA", Name = "Bosnia and Herzegovina"},
new Country() { Code = "BW", Name = "Botswana"},
new Country() { Code = "BV", Name = "Bouvet Island"},
new Country() { Code = "BR", Name = "Brazil"},
new Country() { Code = "IO", Name = "British Indian Ocean Territory"},
new Country() { Code = "BN", Name = "Brunei Darussalam"},
new Country() { Code = "BG", Name = "Bulgaria"},
new Country() { Code = "BF", Name = "Burkina Faso"},
new Country() { Code = "BI", Name = "Burundi"},
new Country() { Code = "KH", Name = "Cambodia"},
new Country() { Code = "CM", Name = "Cameroon"},
new Country() { Code = "CA", Name = "Canada"},
new Country() { Code = "CV", Name = "Cape Verde"},
new Country() { Code = "KY", Name = "Cayman Islands"},
new Country() { Code = "CF", Name = "Central African Republic"},
new Country() { Code = "TD", Name = "Chad"},
new Country() { Code = "CL", Name = "Chile"},
new Country() { Code = "CN", Name = "China"},
new Country() { Code = "CX", Name = "Christmas Island"},
new Country() { Code = "CC", Name = "Cocos (Keeling) Islands"},
new Country() { Code = "CO", Name = "Colombia"},
new Country() { Code = "KM", Name = "Comoros"},
new Country() { Code = "CG", Name = "Congo"},
new Country() { Code = "CD", Name = "Congo, the Democratic Republic of the"},
new Country() { Code = "CK", Name = "Cook Islands"},
new Country() { Code = "CR", Name = "Costa Rica"},
new Country() { Code = "CI", Name = "Côte d'Ivoire"},
new Country() { Code = "HR", Name = "Croatia"},
new Country() { Code = "CU", Name = "Cuba"},
new Country() { Code = "CW", Name = "Curaçao"},
new Country() { Code = "CY", Name = "Cyprus"},
new Country() { Code = "CZ", Name = "Czech Republic"},
new Country() { Code = "DK", Name = "Denmark"},
new Country() { Code = "DJ", Name = "Djibouti"},
new Country() { Code = "DM", Name = "Dominica"},
new Country() { Code = "DO", Name = "Dominican Republic"},
new Country() { Code = "EC", Name = "Ecuador"},
new Country() { Code = "EG", Name = "Egypt"},
new Country() { Code = "SV", Name = "El Salvador"},
new Country() { Code = "GQ", Name = "Equatorial Guinea"},
new Country() { Code = "ER", Name = "Eritrea"},
new Country() { Code = "EE", Name = "Estonia"},
new Country() { Code = "ET", Name = "Ethiopia"},
new Country() { Code = "FK", Name = "Falkland Islands (Malvinas)"},
new Country() { Code = "FO", Name = "Faroe Islands"},
new Country() { Code = "FJ", Name = "Fiji"},
new Country() { Code = "FI", Name = "Finland"},
new Country() { Code = "FR", Name = "France"},
new Country() { Code = "GF", Name = "French Guiana"},
new Country() { Code = "PF", Name = "French Polynesia"},
new Country() { Code = "TF", Name = "French Southern Territories"},
new Country() { Code = "GA", Name = "Gabon"},
new Country() { Code = "GM", Name = "Gambia"},
new Country() { Code = "GE", Name = "Georgia"},
new Country() { Code = "DE", Name = "Germany"},
new Country() { Code = "GH", Name = "Ghana"},
new Country() { Code = "GI", Name = "Gibraltar"},
new Country() { Code = "GR", Name = "Greece"},
new Country() { Code = "GL", Name = "Greenland"},
new Country() { Code = "GD", Name = "Grenada"},
new Country() { Code = "GP", Name = "Guadeloupe"},
new Country() { Code = "GU", Name = "Guam"},
new Country() { Code = "GT", Name = "Guatemala"},
new Country() { Code = "GG", Name = "Guernsey"},
new Country() { Code = "GN", Name = "Guinea"},
new Country() { Code = "GW", Name = "Guinea-Bissau"},
new Country() { Code = "GY", Name = "Guyana"},
new Country() { Code = "HT", Name = "Haiti"},
new Country() { Code = "HM", Name = "Heard Island and McDonald Islands"},
new Country() { Code = "VA", Name = "Holy See (Vatican City State)"},
new Country() { Code = "HN", Name = "Honduras"},
new Country() { Code = "HK", Name = "Hong Kong"},
new Country() { Code = "HU", Name = "Hungary"},
new Country() { Code = "IS", Name = "Iceland"},
new Country() { Code = "IN", Name = "India"},
new Country() { Code = "ID", Name = "Indonesia"},
new Country() { Code = "IR", Name = "Iran, Islamic Republic of"},
new Country() { Code = "IQ", Name = "Iraq"},
new Country() { Code = "IE", Name = "Ireland"},
new Country() { Code = "IM", Name = "Isle of Man"},
new Country() { Code = "IL", Name = "Israel"},
new Country() { Code = "IT", Name = "Italy"},
new Country() { Code = "JM", Name = "Jamaica"},
new Country() { Code = "JP", Name = "Japan"},
new Country() { Code = "JE", Name = "Jersey"},
new Country() { Code = "JO", Name = "Jordan"},
new Country() { Code = "KZ", Name = "Kazakhstan"},
new Country() { Code = "KE", Name = "Kenya"},
new Country() { Code = "KI", Name = "Kiribati"},
new Country() { Code = "KP", Name = "Korea, Democratic People's Republic of"},
new Country() { Code = "KR", Name = "Korea, Republic of"},
new Country() { Code = "KW", Name = "Kuwait"},
new Country() { Code = "KG", Name = "Kyrgyzstan"},
new Country() { Code = "LA", Name = "Lao People's Democratic Republic"},
new Country() { Code = "LV", Name = "Latvia"},
new Country() { Code = "LB", Name = "Lebanon"},
new Country() { Code = "LS", Name = "Lesotho"},
new Country() { Code = "LR", Name = "Liberia"},
new Country() { Code = "LY", Name = "Libya"},
new Country() { Code = "LI", Name = "Liechtenstein"},
new Country() { Code = "LT", Name = "Lithuania"},
new Country() { Code = "LU", Name = "Luxembourg"},
new Country() { Code = "MO", Name = "Macao"},
new Country() { Code = "MK", Name = "Macedonia, the Former Yugoslav Republic of"},
new Country() { Code = "MG", Name = "Madagascar"},
new Country() { Code = "MW", Name = "Malawi"},
new Country() { Code = "MY", Name = "Malaysia"},
new Country() { Code = "MV", Name = "Maldives"},
new Country() { Code = "ML", Name = "Mali"},
new Country() { Code = "MT", Name = "Malta"},
new Country() { Code = "MH", Name = "Marshall Islands"},
new Country() { Code = "MQ", Name = "Martinique"},
new Country() { Code = "MR", Name = "Mauritania"},
new Country() { Code = "MU", Name = "Mauritius"},
new Country() { Code = "YT", Name = "Mayotte"},
new Country() { Code = "MX", Name = "Mexico"},
new Country() { Code = "FM", Name = "Micronesia, Federated States of"},
new Country() { Code = "MD", Name = "Moldova, Republic of"},
new Country() { Code = "MC", Name = "Monaco"},
new Country() { Code = "MN", Name = "Mongolia"},
new Country() { Code = "ME", Name = "Montenegro"},
new Country() { Code = "MS", Name = "Montserrat"},
new Country() { Code = "MA", Name = "Morocco"},
new Country() { Code = "MZ", Name = "Mozambique"},
new Country() { Code = "MM", Name = "Myanmar"},
new Country() { Code = "NA", Name = "Namibia"},
new Country() { Code = "NR", Name = "Nauru"},
new Country() { Code = "NP", Name = "Nepal"},
new Country() { Code = "NL", Name = "Netherlands"},
new Country() { Code = "NC", Name = "New Caledonia"},
new Country() { Code = "NZ", Name = "New Zealand"},
new Country() { Code = "NI", Name = "Nicaragua"},
new Country() { Code = "NE", Name = "Niger"},
new Country() { Code = "NG", Name = "Nigeria"},
new Country() { Code = "NU", Name = "Niue"},
new Country() { Code = "NF", Name = "Norfolk Island"},
new Country() { Code = "MP", Name = "Northern Mariana Islands"},
new Country() { Code = "NO", Name = "Norway"},
new Country() { Code = "OM", Name = "Oman"},
new Country() { Code = "PK", Name = "Pakistan"},
new Country() { Code = "PW", Name = "Palau"},
new Country() { Code = "PS", Name = "Palestine, State of"},
new Country() { Code = "PA", Name = "Panama"},
new Country() { Code = "PG", Name = "Papua New Guinea"},
new Country() { Code = "PY", Name = "Paraguay"},
new Country() { Code = "PE", Name = "Peru"},
new Country() { Code = "PH", Name = "Philippines"},
new Country() { Code = "PN", Name = "Pitcairn"},
new Country() { Code = "PL", Name = "Poland"},
new Country() { Code = "PT", Name = "Portugal"},
new Country() { Code = "PR", Name = "Puerto Rico"},
new Country() { Code = "QA", Name = "Qatar"},
new Country() { Code = "RE", Name = "Réunion"},
new Country() { Code = "RO", Name = "Romania"},
new Country() { Code = "RU", Name = "Russian Federation"},
new Country() { Code = "RW", Name = "Rwanda"},
new Country() { Code = "BL", Name = "Saint Barthélemy"},
new Country() { Code = "SH", Name = "Saint Helena, Ascension and Tristan da Cunha"},
new Country() { Code = "KN", Name = "Saint Kitts and Nevis"},
new Country() { Code = "LC", Name = "Saint Lucia"},
new Country() { Code = "MF", Name = "Saint Martin (French part)"},
new Country() { Code = "PM", Name = "Saint Pierre and Miquelon"},
new Country() { Code = "VC", Name = "Saint Vincent and the Grenadines"},
new Country() { Code = "WS", Name = "Samoa"},
new Country() { Code = "SM", Name = "San Marino"},
new Country() { Code = "ST", Name = "Sao Tome and Principe"},
new Country() { Code = "SA", Name = "Saudi Arabia"},
new Country() { Code = "SN", Name = "Senegal"},
new Country() { Code = "RS", Name = "Serbia"},
new Country() { Code = "SC", Name = "Seychelles"},
new Country() { Code = "SL", Name = "Sierra Leone"},
new Country() { Code = "SG", Name = "Singapore"},
new Country() { Code = "SX", Name = "Sint Maarten (Dutch part)"},
new Country() { Code = "SK", Name = "Slovakia"},
new Country() { Code = "SI", Name = "Slovenia"},
new Country() { Code = "SB", Name = "Solomon Islands"},
new Country() { Code = "SO", Name = "Somalia"},
new Country() { Code = "ZA", Name = "South Africa"},
new Country() { Code = "GS", Name = "South Georgia and the South Sandwich Islands"},
new Country() { Code = "SS", Name = "South Sudan"},
new Country() { Code = "ES", Name = "Spain"},
new Country() { Code = "LK", Name = "Sri Lanka"},
new Country() { Code = "SD", Name = "Sudan"},
new Country() { Code = "SR", Name = "Suriname"},
new Country() { Code = "SJ", Name = "Svalbard and Jan Mayen"},
new Country() { Code = "SZ", Name = "Swaziland"},
new Country() { Code = "SE", Name = "Sweden"},
new Country() { Code = "CH", Name = "Switzerland"},
new Country() { Code = "SY", Name = "Syrian Arab Republic"},
new Country() { Code = "TW", Name = "Taiwan, Province of China"},
new Country() { Code = "TJ", Name = "Tajikistan"},
new Country() { Code = "TZ", Name = "Tanzania, United Republic of"},
new Country() { Code = "TH", Name = "Thailand"},
new Country() { Code = "TL", Name = "Timor-Leste"},
new Country() { Code = "TG", Name = "Togo"},
new Country() { Code = "TK", Name = "Tokelau"},
new Country() { Code = "TO", Name = "Tonga"},
new Country() { Code = "TT", Name = "Trinidad and Tobago"},
new Country() { Code = "TN", Name = "Tunisia"},
new Country() { Code = "TR", Name = "Turkey"},
new Country() { Code = "TM", Name = "Turkmenistan"},
new Country() { Code = "TC", Name = "Turks and Caicos Islands"},
new Country() { Code = "TV", Name = "Tuvalu"},
new Country() { Code = "UG", Name = "Uganda"},
new Country() { Code = "UA", Name = "Ukraine"},
new Country() { Code = "AE", Name = "United Arab Emirates"},
new Country() { Code = "GB", Name = "United Kingdom"},
new Country() { Code = "US", Name = "United States"},
new Country() { Code = "UM", Name = "United States Minor Outlying Islands"},
new Country() { Code = "UY", Name = "Uruguay"},
new Country() { Code = "UZ", Name = "Uzbekistan"},
new Country() { Code = "VU", Name = "Vanuatu"},
new Country() { Code = "VE", Name = "Venezuela, Bolivarian Republic of"},
new Country() { Code = "VN", Name = "Viet Nam"},
new Country() { Code = "VG", Name = "Virgin Islands, British"},
new Country() { Code = "VI", Name = "Virgin Islands, U.S."},
new Country() { Code = "WF", Name = "Wallis and Futuna"},
new Country() { Code = "EH", Name = "Western Sahara"},
new Country() { Code = "YE", Name = "Yemen"},
new Country() { Code = "ZM", Name = "Zambia"},
new Country() { Code = "ZW", Name = "Zimbabwe"},

            });

            _dbContext.Genres.AddRange(new[]
            {
                new MusicGenre() { Name = "Alternative" },
new MusicGenre() { Name = "Alternative Rock" },
new MusicGenre() { Name = "College Rock" },
new MusicGenre() { Name = "Experimental Rock" },
new MusicGenre() { Name = "Goth Rock" },
new MusicGenre() { Name = "Grunge" },
new MusicGenre() { Name = "Hardcore Punk" },
new MusicGenre() { Name = "Hard Rock" },
new MusicGenre() { Name = "Indie Rock" },
new MusicGenre() { Name = "New Wave" },
new MusicGenre() { Name = "Progressive Rock" },
new MusicGenre() { Name = "Punk" },
new MusicGenre() { Name = "Shoegaze" },
new MusicGenre() { Name = "Steampunk" },
new MusicGenre() { Name = "Anime" },
new MusicGenre() { Name = "Blues" },
new MusicGenre() { Name = "Acoustic Blues" },
new MusicGenre() { Name = "Chicago Blues" },
new MusicGenre() { Name = "Classic Blues" },
new MusicGenre() { Name = "Contemporary Blues" },
new MusicGenre() { Name = "Country Blues" },
new MusicGenre() { Name = "Delta Blues" },
new MusicGenre() { Name = "Electric Blues" },
new MusicGenre() { Name = "Children’s Music" },
new MusicGenre() { Name = "Lullabies" },
new MusicGenre() { Name = "Sing-Along" },
new MusicGenre() { Name = "Stories" },
new MusicGenre() { Name = "Classical" },
new MusicGenre() { Name = "Avant-Garde" },
new MusicGenre() { Name = "Baroque" },
new MusicGenre() { Name = "Chamber Music" },
new MusicGenre() { Name = "Chant" },
new MusicGenre() { Name = "Choral" },
new MusicGenre() { Name = "Classical Crossover" },
new MusicGenre() { Name = "Early Music" },
new MusicGenre() { Name = "High Classical" },
new MusicGenre() { Name = "Impressionist" },
new MusicGenre() { Name = "Medieval" },
new MusicGenre() { Name = "Minimalism" },
new MusicGenre() { Name = "Modern Composition" },
new MusicGenre() { Name = "Opera" },
new MusicGenre() { Name = "Orchestral" },
new MusicGenre() { Name = "Renaissance" },
new MusicGenre() { Name = "Romantic" },
new MusicGenre() { Name = "Wedding Music" },
new MusicGenre() { Name = "Comedy" },
new MusicGenre() { Name = "Novelty" },
new MusicGenre() { Name = "Standup Comedy" },
new MusicGenre() { Name = "Country" },
new MusicGenre() { Name = "Alternative Country" },
new MusicGenre() { Name = "Americana" },
new MusicGenre() { Name = "Bluegrass" },
new MusicGenre() { Name = "Contemporary Bluegrass" },
new MusicGenre() { Name = "Contemporary Country" },
new MusicGenre() { Name = "Country Gospel" },
new MusicGenre() { Name = "Honky Tonk" },
new MusicGenre() { Name = "Outlaw Country" },
new MusicGenre() { Name = "Traditional Bluegrass" },
new MusicGenre() { Name = "Traditional Country" },
new MusicGenre() { Name = "Urban Cowboy" },
new MusicGenre() { Name = "Dance / EMD" },
new MusicGenre() { Name = "Breakbeat" },
new MusicGenre() { Name = "Dubstep" },
new MusicGenre() { Name = "Exercise" },
new MusicGenre() { Name = "Garage" },
new MusicGenre() { Name = "Hardcore" },
new MusicGenre() { Name = "Hard Dance" },
new MusicGenre() { Name = "Hi-NRG / Eurodance" },
new MusicGenre() { Name = "House" },
new MusicGenre() { Name = "Jackin House" },
new MusicGenre() { Name = "Jungle/Drum’n'bass" },
new MusicGenre() { Name = "Techno" },
new MusicGenre() { Name = "Trance" },
new MusicGenre() { Name = "Disney" },
new MusicGenre() { Name = "Easy Listening" },
new MusicGenre() { Name = "Bop" },
new MusicGenre() { Name = "Lounge" },
new MusicGenre() { Name = "Swing" },
new MusicGenre() { Name = "Electronic" },
new MusicGenre() { Name = "Ambient" },
new MusicGenre() { Name = "Crunk" },
new MusicGenre() { Name = "Downtempo" },
new MusicGenre() { Name = "Electro" },
new MusicGenre() { Name = "Electronica" },
new MusicGenre() { Name = "Electronic Rock" },
new MusicGenre() { Name = "IDM/Experimental" },
new MusicGenre() { Name = "Industrial" },
new MusicGenre() { Name = "Enka" },
new MusicGenre() { Name = "French Pop" },
new MusicGenre() { Name = "German Folk" },
new MusicGenre() { Name = "German Pop" },
new MusicGenre() { Name = "Fitness & Workout" },
new MusicGenre() { Name = "Hip-Hop/Rap" },
new MusicGenre() { Name = "Alternative Rap" },
new MusicGenre() { Name = "Bounce" },
new MusicGenre() { Name = "Dirty South" },
new MusicGenre() { Name = "East Coast Rap" },
new MusicGenre() { Name = "Gangsta Rap" },
new MusicGenre() { Name = "Hardcore Rap" },
new MusicGenre() { Name = "Hip-Hop" },
new MusicGenre() { Name = "Latin Rap" },
new MusicGenre() { Name = "Old School Rap" },
new MusicGenre() { Name = "Rap" },
new MusicGenre() { Name = "Underground Rap" },
new MusicGenre() { Name = "West Coast Rap" },
new MusicGenre() { Name = "Holiday" },
new MusicGenre() { Name = "Chanukah" },
new MusicGenre() { Name = "Christmas" },
new MusicGenre() { Name = "Christmas: Children’s" },
new MusicGenre() { Name = "Christmas: Classic" },
new MusicGenre() { Name = "Christmas: Classical" },
new MusicGenre() { Name = "Christmas: Jazz" },
new MusicGenre() { Name = "Christmas: Modern" },
new MusicGenre() { Name = "Christmas: Pop" },
new MusicGenre() { Name = "Christmas: R&B" },
new MusicGenre() { Name = "Christmas: Religious" },
new MusicGenre() { Name = "Christmas: Rock" },
new MusicGenre() { Name = "Easter" },
new MusicGenre() { Name = "Halloween" },
new MusicGenre() { Name = "Holiday: Other" },
new MusicGenre() { Name = "Thanksgiving" },
new MusicGenre() { Name = "Indie Pop" },
new MusicGenre() { Name = "Industrial" },
new MusicGenre() { Name = "Inspirational – Christian & Gospel" },
new MusicGenre() { Name = "CCM" },
new MusicGenre() { Name = "Christian Metal" },
new MusicGenre() { Name = "Christian Pop" },
new MusicGenre() { Name = "Christian Rap" },
new MusicGenre() { Name = "Christian Rock" },
new MusicGenre() { Name = "Classic Christian" },
new MusicGenre() { Name = "Contemporary Gospel" },
new MusicGenre() { Name = "Gospel" },
new MusicGenre() { Name = "Christian & Gospel" },
new MusicGenre() { Name = "Praise & Worship" },
new MusicGenre() { Name = "Qawwali" },
new MusicGenre() { Name = "Southern Gospel" },
new MusicGenre() { Name = "Traditional Gospel" },
new MusicGenre() { Name = "Instrumental" },
new MusicGenre() { Name = "March (Marching Band)" },
new MusicGenre() { Name = "J-Pop" },
new MusicGenre() { Name = "J-Rock" },
new MusicGenre() { Name = "J-Synth" },
new MusicGenre() { Name = "J-Ska" },
new MusicGenre() { Name = "J-Punk" },
new MusicGenre() { Name = "Jazz" },
new MusicGenre() { Name = "Acid Jazz" },
new MusicGenre() { Name = "Avant-Garde Jazz" },
new MusicGenre() { Name = "Big Band" },
new MusicGenre() { Name = "Blue Note" },
new MusicGenre() { Name = "Contemporary Jazz" },
new MusicGenre() { Name = "Cool" },
new MusicGenre() { Name = "Crossover Jazz" },
new MusicGenre() { Name = "Dixieland" },
new MusicGenre() { Name = "Ethio-jazz" },
new MusicGenre() { Name = "Fusion" },
new MusicGenre() { Name = "Hard Bop" },
new MusicGenre() { Name = "Latin Jazz" },
new MusicGenre() { Name = "Mainstream Jazz" },
new MusicGenre() { Name = "Ragtime" },
new MusicGenre() { Name = "Smooth Jazz" },
new MusicGenre() { Name = "Trad Jazz" },
new MusicGenre() { Name = "K-Pop" },
new MusicGenre() { Name = "Karaoke" },
new MusicGenre() { Name = "Kayokyoku" },
new MusicGenre() { Name = "Latino" },
new MusicGenre() { Name = "Alternativo & Rock Latino" },
new MusicGenre() { Name = "Baladas y Boleros" },
new MusicGenre() { Name = "Brazilian" },
new MusicGenre() { Name = "Contemporary Latin" },
new MusicGenre() { Name = "Latin Jazz" },
new MusicGenre() { Name = "Pop Latino" },
new MusicGenre() { Name = "Raíces" },
new MusicGenre() { Name = "Reggaeton y Hip-Hop" },
new MusicGenre() { Name = "Regional Mexicano" },
new MusicGenre() { Name = "Salsa y Tropical" },
new MusicGenre() { Name = "New Age" },
new MusicGenre() { Name = "Environmental" },
new MusicGenre() { Name = "Healing" },
new MusicGenre() { Name = "Meditation" },
new MusicGenre() { Name = "Nature" },
new MusicGenre() { Name = "Relaxation" },
new MusicGenre() { Name = "Travel" },
new MusicGenre() { Name = "Opera" },
new MusicGenre() { Name = "Pop" },
new MusicGenre() { Name = "Adult Contemporary" },
new MusicGenre() { Name = "Britpop" },
new MusicGenre() { Name = "Pop/Rock" },
new MusicGenre() { Name = "Soft Rock" },
new MusicGenre() { Name = "Teen Pop" },
new MusicGenre() { Name = "R&B/Soul" },
new MusicGenre() { Name = "Contemporary R&B" },
new MusicGenre() { Name = "Disco" },
new MusicGenre() { Name = "Doo Wop" },
new MusicGenre() { Name = "Funk" },
new MusicGenre() { Name = "Motown" },
new MusicGenre() { Name = "Neo-Soul" },
new MusicGenre() { Name = "Quiet Storm" },
new MusicGenre() { Name = "Soul" },
new MusicGenre() { Name = "Reggae" },
new MusicGenre() { Name = "Dancehall" },
new MusicGenre() { Name = "Dub" },
new MusicGenre() { Name = "Roots Reggae" },
new MusicGenre() { Name = "Ska" },
new MusicGenre() { Name = "Rock" },
new MusicGenre() { Name = "Adult Alternative" },
new MusicGenre() { Name = "American Trad Rock" },
new MusicGenre() { Name = "Arena Rock" },
new MusicGenre() { Name = "Blues-Rock" },
new MusicGenre() { Name = "British Invasion" },
new MusicGenre() { Name = "Death Metal/Black Metal" },
new MusicGenre() { Name = "Glam Rock" },
new MusicGenre() { Name = "Hair Metal" },
new MusicGenre() { Name = "Hard Rock" },
new MusicGenre() { Name = "Metal" },
new MusicGenre() { Name = "Jam Bands" },
new MusicGenre() { Name = "Prog-Rock/Art Rock" },
new MusicGenre() { Name = "Psychedelic" },
new MusicGenre() { Name = "Rock & Roll" },
new MusicGenre() { Name = "Rockabilly" },
new MusicGenre() { Name = "Roots Rock" },
new MusicGenre() { Name = "Singer/Songwriter" },
new MusicGenre() { Name = "Southern Rock" },
new MusicGenre() { Name = "Surf" },
new MusicGenre() { Name = "Tex-Mex" },
new MusicGenre() { Name = "Singer/Songwriter" },
new MusicGenre() { Name = "Alternative Folk" },
new MusicGenre() { Name = "Contemporary Folk" },
new MusicGenre() { Name = "Contemporary Singer/Songwriter" },
new MusicGenre() { Name = "Folk-Rock" },
new MusicGenre() { Name = "New Acoustic" },
new MusicGenre() { Name = "Traditional Folk" },
new MusicGenre() { Name = "Soundtrack" },
new MusicGenre() { Name = "Foreign Cinema" },
new MusicGenre() { Name = "Musicals" },
new MusicGenre() { Name = "Original Score" },
new MusicGenre() { Name = "Soundtrack" },
new MusicGenre() { Name = "TV Soundtrack" },
new MusicGenre() { Name = "Spoken Word" },
new MusicGenre() { Name = "Tex-Mex / Tejano" },
new MusicGenre() { Name = "Chicano" },
new MusicGenre() { Name = "Classic" },
new MusicGenre() { Name = "Conjunto" },
new MusicGenre() { Name = "Conjunto Progressive" },
new MusicGenre() { Name = "New Mex" },
new MusicGenre() { Name = "Tex-Mex" },
new MusicGenre() { Name = "Vocal" },
new MusicGenre() { Name = "Barbershop" },
new MusicGenre() { Name = "Doo-wop" },
new MusicGenre() { Name = "Standards" },
new MusicGenre() { Name = "Traditional Pop" },
new MusicGenre() { Name = "Vocal Jazz" },
new MusicGenre() { Name = "Vocal Pop" },
new MusicGenre() { Name = "World" },
new MusicGenre() { Name = "Africa" },
new MusicGenre() { Name = "Afro-Beat" },
new MusicGenre() { Name = "Afro-Pop" },
new MusicGenre() { Name = "Asia" },
new MusicGenre() { Name = "Australia" },
new MusicGenre() { Name = "Bossa Nova" },
new MusicGenre() { Name = "Cajun" },
new MusicGenre() { Name = "Caribbean" },
new MusicGenre() { Name = "Celtic" },
new MusicGenre() { Name = "Celtic Folk" },
new MusicGenre() { Name = "Contemporary Celtic" },
new MusicGenre() { Name = "Drinking Songs" },
new MusicGenre() { Name = "Drone" },
new MusicGenre() { Name = "Europe" },
new MusicGenre() { Name = "France" },
new MusicGenre() { Name = "Hawaii" },
new MusicGenre() { Name = "Indian Pop" },
new MusicGenre() { Name = "Japan" },
new MusicGenre() { Name = "Japanese Pop" },
new MusicGenre() { Name = "Klezmer" },
new MusicGenre() { Name = "Middle East" },
new MusicGenre() { Name = "North America" },
new MusicGenre() { Name = "Polka" },
new MusicGenre() { Name = "South Africa" },
new MusicGenre() { Name = "South America" },
new MusicGenre() { Name = "Traditional Celtic" },
new MusicGenre() { Name = "Worldbeat" },
new MusicGenre() { Name = "Zydeco" },

            });

            await _dbContext.SaveChangesAsync(cancellationToken);

            _log.LogInformation("Seeded completed!");
        }
    }
}
