using Microsoft.Extensions.Logging;
using MusicUniverse.Application.Common.Interfaces;
using MusicUniverse.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace MusicUniverse.Application.System.Seed
{
    public class DbSeedService : IDbSeedService
    {
        private readonly IMusicUniverseDbContext _dbContext;

        private readonly ILogger<DbSeedService> _log;

        public DbSeedService(IMusicUniverseDbContext dbContext, ILogger<DbSeedService> log)
        {
            _dbContext = dbContext;
            _log = log;
        }

        public async Task SeedAsync(CancellationToken cancellationToken)
        {
            _log.LogInformation("Seeding...");

            _dbContext.Countries.AddRange(new[]
            {
                new Country() { Id = 1,Code = "AF", Name = "Afghanistan"},
                new Country() { Id = 2,Code = "AX", Name = "Åland Islands"},
                new Country() { Id = 3,Code = "AL", Name = "Albania"},
                new Country() { Id = 4,Code = "DZ", Name = "Algeria"},
                new Country() { Id = 5,Code = "AS", Name = "American Samoa"},
                new Country() { Id = 6,Code = "AD", Name = "Andorra"},
                new Country() { Id = 7,Code = "AO", Name = "Angola"},
                new Country() { Id = 8,Code = "AI", Name = "Anguilla"},
                new Country() { Id = 9,Code = "AQ", Name = "Antarctica"},
                new Country() { Id = 10,Code = "AG", Name = "Antigua and Barbuda"},
                new Country() { Id = 11,Code = "AR", Name = "Argentina"},
                new Country() { Id = 12,Code = "AM", Name = "Armenia"},
                new Country() { Id = 13,Code = "AW", Name = "Aruba"},
                new Country() { Id = 14,Code = "AU", Name = "Australia"},
                new Country() { Id = 15,Code = "AT", Name = "Austria"},
                new Country() { Id = 16,Code = "AZ", Name = "Azerbaijan"},
                new Country() { Id = 17,Code = "BS", Name = "Bahamas"},
                new Country() { Id = 18,Code = "BH", Name = "Bahrain"},
                new Country() { Id = 19,Code = "BD", Name = "Bangladesh"},
                new Country() { Id = 20,Code = "BB", Name = "Barbados"},
                new Country() { Id = 21,Code = "BY", Name = "Belarus"},
                new Country() { Id = 22,Code = "BE", Name = "Belgium"},
                new Country() { Id = 23,Code = "BZ", Name = "Belize"},
                new Country() { Id = 24,Code = "BJ", Name = "Benin"},
                new Country() { Id = 25,Code = "BM", Name = "Bermuda"},
                new Country() { Id = 26,Code = "BT", Name = "Bhutan"},
                new Country() { Id = 27,Code = "BO", Name = "Bolivia, Plurinational State of"},
                new Country() { Id = 28,Code = "BQ", Name = "Bonaire, Sint Eustatius and Saba"},
                new Country() { Id = 29,Code = "BA", Name = "Bosnia and Herzegovina"},
                new Country() { Id = 30,Code = "BW", Name = "Botswana"},
                new Country() { Id = 31,Code = "BV", Name = "Bouvet Island"},
                new Country() { Id = 32,Code = "BR", Name = "Brazil"},
                new Country() { Id = 33,Code = "IO", Name = "British Indian Ocean Territory"},
                new Country() { Id = 34,Code = "BN", Name = "Brunei Darussalam"},
                new Country() { Id = 35,Code = "BG", Name = "Bulgaria"},
                new Country() { Id = 36,Code = "BF", Name = "Burkina Faso"},
                new Country() { Id = 37,Code = "BI", Name = "Burundi"},
                new Country() { Id = 38,Code = "KH", Name = "Cambodia"},
                new Country() { Id = 39,Code = "CM", Name = "Cameroon"},
                new Country() { Id = 40,Code = "CA", Name = "Canada"},
                new Country() { Id = 41,Code = "CV", Name = "Cape Verde"},
                new Country() { Id = 42,Code = "KY", Name = "Cayman Islands"},
                new Country() { Id = 43,Code = "CF", Name = "Central African Republic"},
                new Country() { Id = 44,Code = "TD", Name = "Chad"},
                new Country() { Id = 45,Code = "CL", Name = "Chile"},
                new Country() { Id = 46,Code = "CN", Name = "China"},
                new Country() { Id = 47,Code = "CX", Name = "Christmas Island"},
                new Country() { Id = 48,Code = "CC", Name = "Cocos (Keeling) Islands"},
                new Country() { Id = 49,Code = "CO", Name = "Colombia"},
                new Country() { Id = 50,Code = "KM", Name = "Comoros"},
                new Country() { Id = 51,Code = "CG", Name = "Congo"},
                new Country() { Id = 52,Code = "CD", Name = "Congo, the Democratic Republic of the"},
                new Country() { Id = 53,Code = "CK", Name = "Cook Islands"},
                new Country() { Id = 54,Code = "CR", Name = "Costa Rica"},
                new Country() { Id = 55,Code = "CI", Name = "Côte d'Ivoire"},
                new Country() { Id = 56,Code = "HR", Name = "Croatia"},
                new Country() { Id = 57,Code = "CU", Name = "Cuba"},
                new Country() { Id = 58,Code = "CW", Name = "Curaçao"},
                new Country() { Id = 59,Code = "CY", Name = "Cyprus"},
                new Country() { Id = 60,Code = "CZ", Name = "Czech Republic"},
                new Country() { Id = 61,Code = "DK", Name = "Denmark"},
                new Country() { Id = 62,Code = "DJ", Name = "Djibouti"},
                new Country() { Id = 63,Code = "DM", Name = "Dominica"},
                new Country() { Id = 64,Code = "DO", Name = "Dominican Republic"},
                new Country() { Id = 65,Code = "EC", Name = "Ecuador"},
                new Country() { Id = 66,Code = "EG", Name = "Egypt"},
                new Country() { Id = 67,Code = "SV", Name = "El Salvador"},
                new Country() { Id = 68,Code = "GQ", Name = "Equatorial Guinea"},
                new Country() { Id = 69,Code = "ER", Name = "Eritrea"},
                new Country() { Id = 70,Code = "EE", Name = "Estonia"},
                new Country() { Id = 71,Code = "ET", Name = "Ethiopia"},
                new Country() { Id = 72,Code = "FK", Name = "Falkland Islands (Malvinas)"},
                new Country() { Id = 73,Code = "FO", Name = "Faroe Islands"},
                new Country() { Id = 74,Code = "FJ", Name = "Fiji"},
                new Country() { Id = 75,Code = "FI", Name = "Finland"},
                new Country() { Id = 76,Code = "FR", Name = "France"},
                new Country() { Id = 77,Code = "GF", Name = "French Guiana"},
                new Country() { Id = 78,Code = "PF", Name = "French Polynesia"},
                new Country() { Id = 79,Code = "TF", Name = "French Southern Territories"},
                new Country() { Id = 80,Code = "GA", Name = "Gabon"},
                new Country() { Id = 81,Code = "GM", Name = "Gambia"},
                new Country() { Id = 82,Code = "GE", Name = "Georgia"},
                new Country() { Id = 83,Code = "DE", Name = "Germany"},
                new Country() { Id = 84,Code = "GH", Name = "Ghana"},
                new Country() { Id = 85,Code = "GI", Name = "Gibraltar"},
                new Country() { Id = 86,Code = "GR", Name = "Greece"},
                new Country() { Id = 87,Code = "GL", Name = "Greenland"},
                new Country() { Id = 88,Code = "GD", Name = "Grenada"},
                new Country() { Id = 89,Code = "GP", Name = "Guadeloupe"},
                new Country() { Id = 90,Code = "GU", Name = "Guam"},
                new Country() { Id = 91,Code = "GT", Name = "Guatemala"},
                new Country() { Id = 92,Code = "GG", Name = "Guernsey"},
                new Country() { Id = 93,Code = "GN", Name = "Guinea"},
                new Country() { Id = 94,Code = "GW", Name = "Guinea-Bissau"},
                new Country() { Id = 95,Code = "GY", Name = "Guyana"},
                new Country() { Id = 96,Code = "HT", Name = "Haiti"},
                new Country() { Id = 97,Code = "HM", Name = "Heard Island and McDonald Islands"},
                new Country() { Id = 98,Code = "VA", Name = "Holy See (Vatican City State)"},
                new Country() { Id = 99,Code = "HN", Name = "Honduras"},
                new Country() { Id = 100,Code = "HK", Name = "Hong Kong"},
                new Country() { Id = 101,Code = "HU", Name = "Hungary"},
                new Country() { Id = 102,Code = "IS", Name = "Iceland"},
                new Country() { Id = 103,Code = "IN", Name = "India"},
                new Country() { Id = 104,Code = "ID", Name = "Indonesia"},
                new Country() { Id = 105,Code = "IR", Name = "Iran, Islamic Republic of"},
                new Country() { Id = 106,Code = "IQ", Name = "Iraq"},
                new Country() { Id = 107,Code = "IE", Name = "Ireland"},
                new Country() { Id = 108,Code = "IM", Name = "Isle of Man"},
                new Country() { Id = 109,Code = "IL", Name = "Israel"},
                new Country() { Id = 110,Code = "IT", Name = "Italy"},
                new Country() { Id = 111,Code = "JM", Name = "Jamaica"},
                new Country() { Id = 112,Code = "JP", Name = "Japan"},
                new Country() { Id = 113,Code = "JE", Name = "Jersey"},
                new Country() { Id = 114,Code = "JO", Name = "Jordan"},
                new Country() { Id = 115,Code = "KZ", Name = "Kazakhstan"},
                new Country() { Id = 116,Code = "KE", Name = "Kenya"},
                new Country() { Id = 117,Code = "KI", Name = "Kiribati"},
                new Country() { Id = 118,Code = "KP", Name = "Korea, Democratic People's Republic of"},
                new Country() { Id = 119,Code = "KR", Name = "Korea, Republic of"},
                new Country() { Id = 120,Code = "KW", Name = "Kuwait"},
                new Country() { Id = 121,Code = "KG", Name = "Kyrgyzstan"},
                new Country() { Id = 122,Code = "LA", Name = "Lao People's Democratic Republic"},
                new Country() { Id = 123,Code = "LV", Name = "Latvia"},
                new Country() { Id = 124,Code = "LB", Name = "Lebanon"},
                new Country() { Id = 125,Code = "LS", Name = "Lesotho"},
                new Country() { Id = 126,Code = "LR", Name = "Liberia"},
                new Country() { Id = 127,Code = "LY", Name = "Libya"},
                new Country() { Id = 128,Code = "LI", Name = "Liechtenstein"},
                new Country() { Id = 129,Code = "LT", Name = "Lithuania"},
                new Country() { Id = 130,Code = "LU", Name = "Luxembourg"},
                new Country() { Id = 131,Code = "MO", Name = "Macao"},
                new Country() { Id = 132,Code = "MK", Name = "Macedonia, the Former Yugoslav Republic of"},
                new Country() { Id = 133,Code = "MG", Name = "Madagascar"},
                new Country() { Id = 134,Code = "MW", Name = "Malawi"},
                new Country() { Id = 135,Code = "MY", Name = "Malaysia"},
                new Country() { Id = 136,Code = "MV", Name = "Maldives"},
                new Country() { Id = 137,Code = "ML", Name = "Mali"},
                new Country() { Id = 138,Code = "MT", Name = "Malta"},
                new Country() { Id = 139,Code = "MH", Name = "Marshall Islands"},
                new Country() { Id = 140,Code = "MQ", Name = "Martinique"},
                new Country() { Id = 141,Code = "MR", Name = "Mauritania"},
                new Country() { Id = 142,Code = "MU", Name = "Mauritius"},
                new Country() { Id = 143,Code = "YT", Name = "Mayotte"},
                new Country() { Id = 144,Code = "MX", Name = "Mexico"},
                new Country() { Id = 145,Code = "FM", Name = "Micronesia, Federated States of"},
                new Country() { Id = 146,Code = "MD", Name = "Moldova, Republic of"},
                new Country() { Id = 147,Code = "MC", Name = "Monaco"},
                new Country() { Id = 148,Code = "MN", Name = "Mongolia"},
                new Country() { Id = 149,Code = "ME", Name = "Montenegro"},
                new Country() { Id = 150,Code = "MS", Name = "Montserrat"},
                new Country() { Id = 151,Code = "MA", Name = "Morocco"},
                new Country() { Id = 152,Code = "MZ", Name = "Mozambique"},
                new Country() { Id = 153,Code = "MM", Name = "Myanmar"},
                new Country() { Id = 154,Code = "NA", Name = "Namibia"},
                new Country() { Id = 155,Code = "NR", Name = "Nauru"},
                new Country() { Id = 156,Code = "NP", Name = "Nepal"},
                new Country() { Id = 157,Code = "NL", Name = "Netherlands"},
                new Country() { Id = 158,Code = "NC", Name = "New Caledonia"},
                new Country() { Id = 159,Code = "NZ", Name = "New Zealand"},
                new Country() { Id = 160,Code = "NI", Name = "Nicaragua"},
                new Country() { Id = 161,Code = "NE", Name = "Niger"},
                new Country() { Id = 162,Code = "NG", Name = "Nigeria"},
                new Country() { Id = 163,Code = "NU", Name = "Niue"},
                new Country() { Id = 164,Code = "NF", Name = "Norfolk Island"},
                new Country() { Id = 165,Code = "MP", Name = "Northern Mariana Islands"},
                new Country() { Id = 166,Code = "NO", Name = "Norway"},
                new Country() { Id = 167,Code = "OM", Name = "Oman"},
                new Country() { Id = 168,Code = "PK", Name = "Pakistan"},
                new Country() { Id = 169,Code = "PW", Name = "Palau"},
                new Country() { Id = 170,Code = "PS", Name = "Palestine, State of"},
                new Country() { Id = 171,Code = "PA", Name = "Panama"},
                new Country() { Id = 172,Code = "PG", Name = "Papua New Guinea"},
                new Country() { Id = 173,Code = "PY", Name = "Paraguay"},
                new Country() { Id = 174,Code = "PE", Name = "Peru"},
                new Country() { Id = 175,Code = "PH", Name = "Philippines"},
                new Country() { Id = 176,Code = "PN", Name = "Pitcairn"},
                new Country() { Id = 177,Code = "PL", Name = "Poland"},
                new Country() { Id = 178,Code = "PT", Name = "Portugal"},
                new Country() { Id = 179,Code = "PR", Name = "Puerto Rico"},
                new Country() { Id = 180,Code = "QA", Name = "Qatar"},
                new Country() { Id = 181,Code = "RE", Name = "Réunion"},
                new Country() { Id = 182,Code = "RO", Name = "Romania"},
                new Country() { Id = 183,Code = "RU", Name = "Russian Federation"},
                new Country() { Id = 184,Code = "RW", Name = "Rwanda"},
                new Country() { Id = 185,Code = "BL", Name = "Saint Barthélemy"},
                new Country() { Id = 186,Code = "SH", Name = "Saint Helena, Ascension and Tristan da Cunha"},
                new Country() { Id = 187,Code = "KN", Name = "Saint Kitts and Nevis"},
                new Country() { Id = 188,Code = "LC", Name = "Saint Lucia"},
                new Country() { Id = 189,Code = "MF", Name = "Saint Martin (French part)"},
                new Country() { Id = 190,Code = "PM", Name = "Saint Pierre and Miquelon"},
                new Country() { Id = 191,Code = "VC", Name = "Saint Vincent and the Grenadines"},
                new Country() { Id = 192,Code = "WS", Name = "Samoa"},
                new Country() { Id = 193,Code = "SM", Name = "San Marino"},
                new Country() { Id = 194,Code = "ST", Name = "Sao Tome and Principe"},
                new Country() { Id = 195,Code = "SA", Name = "Saudi Arabia"},
                new Country() { Id = 196,Code = "SN", Name = "Senegal"},
                new Country() { Id = 197,Code = "RS", Name = "Serbia"},
                new Country() { Id = 198,Code = "SC", Name = "Seychelles"},
                new Country() { Id = 199,Code = "SL", Name = "Sierra Leone"},
                new Country() { Id = 200,Code = "SG", Name = "Singapore"},
                new Country() { Id = 201,Code = "SX", Name = "Sint Maarten (Dutch part)"},
                new Country() { Id = 202,Code = "SK", Name = "Slovakia"},
                new Country() { Id = 203,Code = "SI", Name = "Slovenia"},
                new Country() { Id = 204,Code = "SB", Name = "Solomon Islands"},
                new Country() { Id = 205,Code = "SO", Name = "Somalia"},
                new Country() { Id = 206,Code = "ZA", Name = "South Africa"},
                new Country() { Id = 207,Code = "GS", Name = "South Georgia and the South Sandwich Islands"},
                new Country() { Id = 208,Code = "SS", Name = "South Sudan"},
                new Country() { Id = 209,Code = "ES", Name = "Spain"},
                new Country() { Id = 210,Code = "LK", Name = "Sri Lanka"},
                new Country() { Id = 211,Code = "SD", Name = "Sudan"},
                new Country() { Id = 212,Code = "SR", Name = "Suriname"},
                new Country() { Id = 213,Code = "SJ", Name = "Svalbard and Jan Mayen"},
                new Country() { Id = 214,Code = "SZ", Name = "Swaziland"},
                new Country() { Id = 215,Code = "SE", Name = "Sweden"},
                new Country() { Id = 216,Code = "CH", Name = "Switzerland"},
                new Country() { Id = 217,Code = "SY", Name = "Syrian Arab Republic"},
                new Country() { Id = 218,Code = "TW", Name = "Taiwan, Province of China"},
                new Country() { Id = 219,Code = "TJ", Name = "Tajikistan"},
                new Country() { Id = 220,Code = "TZ", Name = "Tanzania, United Republic of"},
                new Country() { Id = 221,Code = "TH", Name = "Thailand"},
                new Country() { Id = 222,Code = "TL", Name = "Timor-Leste"},
                new Country() { Id = 223,Code = "TG", Name = "Togo"},
                new Country() { Id = 224,Code = "TK", Name = "Tokelau"},
                new Country() { Id = 225,Code = "TO", Name = "Tonga"},
                new Country() { Id = 226,Code = "TT", Name = "Trinidad and Tobago"},
                new Country() { Id = 227,Code = "TN", Name = "Tunisia"},
                new Country() { Id = 228,Code = "TR", Name = "Turkey"},
                new Country() { Id = 229,Code = "TM", Name = "Turkmenistan"},
                new Country() { Id = 230,Code = "TC", Name = "Turks and Caicos Islands"},
                new Country() { Id = 231,Code = "TV", Name = "Tuvalu"},
                new Country() { Id = 232,Code = "UG", Name = "Uganda"},
                new Country() { Id = 233,Code = "UA", Name = "Ukraine"},
                new Country() { Id = 234,Code = "AE", Name = "United Arab Emirates"},
                new Country() { Id = 235,Code = "GB", Name = "United Kingdom"},
                new Country() { Id = 236,Code = "US", Name = "United States"},
                new Country() { Id = 237,Code = "UM", Name = "United States Minor Outlying Islands"},
                new Country() { Id = 238,Code = "UY", Name = "Uruguay"},
                new Country() { Id = 239,Code = "UZ", Name = "Uzbekistan"},
                new Country() { Id = 240,Code = "VU", Name = "Vanuatu"},
                new Country() { Id = 241,Code = "VE", Name = "Venezuela, Bolivarian Republic of"},
                new Country() { Id = 242,Code = "VN", Name = "Viet Nam"},
                new Country() { Id = 243,Code = "VG", Name = "Virgin Islands, British"},
                new Country() { Id = 244,Code = "VI", Name = "Virgin Islands, U.S."},
                new Country() { Id = 245,Code = "WF", Name = "Wallis and Futuna"},
                new Country() { Id = 246,Code = "EH", Name = "Western Sahara"},
                new Country() { Id = 247,Code = "YE", Name = "Yemen"},
                new Country() { Id = 248,Code = "ZM", Name = "Zambia"},
                new Country() { Id = 249,Code = "ZW", Name = "Zimbabwe"}
            });

            _dbContext.Genres.AddRange(new[]
            {
                new MusicGenre() { Id = 1, Name = "Alternative" },
                new MusicGenre() { Id = 2, Name = "Alternative Rock" },
                new MusicGenre() { Id = 3, Name = "College Rock" },
                new MusicGenre() { Id = 4, Name = "Experimental Rock" },
                new MusicGenre() { Id = 5, Name = "Goth Rock" },
                new MusicGenre() { Id = 6, Name = "Grunge" },
                new MusicGenre() { Id = 7, Name = "Hardcore Punk" },
                new MusicGenre() { Id = 8, Name = "Hard Rock" },
                new MusicGenre() { Id = 9, Name = "Indie Rock" },
                new MusicGenre() { Id = 10, Name = "New Wave" },
                new MusicGenre() { Id = 11, Name = "Progressive Rock" },
                new MusicGenre() { Id = 12, Name = "Punk" },
                new MusicGenre() { Id = 13, Name = "Shoegaze" },
                new MusicGenre() { Id = 14, Name = "Steampunk" },
                new MusicGenre() { Id = 15, Name = "Anime" },
                new MusicGenre() { Id = 16, Name = "Blues" },
                new MusicGenre() { Id = 17, Name = "Acoustic Blues" },
                new MusicGenre() { Id = 18, Name = "Chicago Blues" },
                new MusicGenre() { Id = 19, Name = "Classic Blues" },
                new MusicGenre() { Id = 20, Name = "Contemporary Blues" },
                new MusicGenre() { Id = 21, Name = "Country Blues" },
                new MusicGenre() { Id = 22, Name = "Delta Blues" },
                new MusicGenre() { Id = 23, Name = "Electric Blues" },
                new MusicGenre() { Id = 24, Name = "Children’s Music" },
                new MusicGenre() { Id = 25, Name = "Lullabies" },
                new MusicGenre() { Id = 26, Name = "Sing-Along" },
                new MusicGenre() { Id = 27, Name = "Stories" },
                new MusicGenre() { Id = 28, Name = "Classical" },
                new MusicGenre() { Id = 29, Name = "Avant-Garde" },
                new MusicGenre() { Id = 30, Name = "Baroque" },
                new MusicGenre() { Id = 31, Name = "Chamber Music" },
                new MusicGenre() { Id = 32, Name = "Chant" },
                new MusicGenre() { Id = 33, Name = "Choral" },
                new MusicGenre() { Id = 34, Name = "Classical Crossover" },
                new MusicGenre() { Id = 35, Name = "Early Music" },
                new MusicGenre() { Id = 36, Name = "High Classical" },
                new MusicGenre() { Id = 37, Name = "Impressionist" },
                new MusicGenre() { Id = 38, Name = "Medieval" },
                new MusicGenre() { Id = 39, Name = "Minimalism" },
                new MusicGenre() { Id = 40, Name = "Modern Composition" },
                new MusicGenre() { Id = 41, Name = "Opera" },
                new MusicGenre() { Id = 42, Name = "Orchestral" },
                new MusicGenre() { Id = 43, Name = "Renaissance" },
                new MusicGenre() { Id = 44, Name = "Romantic" },
                new MusicGenre() { Id = 45, Name = "Wedding Music" },
                new MusicGenre() { Id = 46, Name = "Comedy" },
                new MusicGenre() { Id = 47, Name = "Novelty" },
                new MusicGenre() { Id = 48, Name = "Standup Comedy" },
                new MusicGenre() { Id = 49, Name = "Country" },
                new MusicGenre() { Id = 50, Name = "Alternative Country" },
                new MusicGenre() { Id = 51, Name = "Americana" },
                new MusicGenre() { Id = 52, Name = "Bluegrass" },
                new MusicGenre() { Id = 53, Name = "Contemporary Bluegrass" },
                new MusicGenre() { Id = 54, Name = "Contemporary Country" },
                new MusicGenre() { Id = 55, Name = "Country Gospel" },
                new MusicGenre() { Id = 56, Name = "Honky Tonk" },
                new MusicGenre() { Id = 57, Name = "Outlaw Country" },
                new MusicGenre() { Id = 58, Name = "Traditional Bluegrass" },
                new MusicGenre() { Id = 59, Name = "Traditional Country" },
                new MusicGenre() { Id = 60, Name = "Urban Cowboy" },
                new MusicGenre() { Id = 61, Name = "Dance / EMD" },
                new MusicGenre() { Id = 62, Name = "Breakbeat" },
                new MusicGenre() { Id = 63, Name = "Dubstep" },
                new MusicGenre() { Id = 64, Name = "Exercise" },
                new MusicGenre() { Id = 65, Name = "Garage" },
                new MusicGenre() { Id = 66, Name = "Hardcore" },
                new MusicGenre() { Id = 67, Name = "Hard Dance" },
                new MusicGenre() { Id = 68, Name = "Hi-NRG / Eurodance" },
                new MusicGenre() { Id = 69, Name = "House" },
                new MusicGenre() { Id = 70, Name = "Jackin House" },
                new MusicGenre() { Id = 71, Name = "Jungle/Drum’n'bass" },
                new MusicGenre() { Id = 72, Name = "Techno" },
                new MusicGenre() { Id = 73, Name = "Trance" },
                new MusicGenre() { Id = 74, Name = "Disney" },
                new MusicGenre() { Id = 75, Name = "Easy Listening" },
                new MusicGenre() { Id = 76, Name = "Bop" },
                new MusicGenre() { Id = 77, Name = "Lounge" },
                new MusicGenre() { Id = 78, Name = "Swing" },
                new MusicGenre() { Id = 79, Name = "Electronic" },
                new MusicGenre() { Id = 80, Name = "Ambient" },
                new MusicGenre() { Id = 81, Name = "Crunk" },
                new MusicGenre() { Id = 82, Name = "Downtempo" },
                new MusicGenre() { Id = 83, Name = "Electro" },
                new MusicGenre() { Id = 84, Name = "Electronica" },
                new MusicGenre() { Id = 85, Name = "Electronic Rock" },
                new MusicGenre() { Id = 86, Name = "IDM/Experimental" },
                new MusicGenre() { Id = 87, Name = "Industrial" },
                new MusicGenre() { Id = 88, Name = "Enka" },
                new MusicGenre() { Id = 89, Name = "French Pop" },
                new MusicGenre() { Id = 90, Name = "German Folk" },
                new MusicGenre() { Id = 91, Name = "German Pop" },
                new MusicGenre() { Id = 92, Name = "Fitness & Workout" },
                new MusicGenre() { Id = 93, Name = "Hip-Hop/Rap" },
                new MusicGenre() { Id = 94, Name = "Alternative Rap" },
                new MusicGenre() { Id = 95, Name = "Bounce" },
                new MusicGenre() { Id = 96, Name = "Dirty South" },
                new MusicGenre() { Id = 97, Name = "East Coast Rap" },
                new MusicGenre() { Id = 98, Name = "Gangsta Rap" },
                new MusicGenre() { Id = 99, Name = "Hardcore Rap" },
                new MusicGenre() { Id = 100, Name = "Hip-Hop" },
                new MusicGenre() { Id = 101, Name = "Latin Rap" },
                new MusicGenre() { Id = 102, Name = "Old School Rap" },
                new MusicGenre() { Id = 103, Name = "Rap" },
                new MusicGenre() { Id = 104, Name = "Underground Rap" },
                new MusicGenre() { Id = 105, Name = "West Coast Rap" },
                new MusicGenre() { Id = 106, Name = "Holiday" },
                new MusicGenre() { Id = 107, Name = "Chanukah" },
                new MusicGenre() { Id = 108, Name = "Christmas" },
                new MusicGenre() { Id = 109, Name = "Christmas: Children’s" },
                new MusicGenre() { Id = 110, Name = "Christmas: Classic" },
                new MusicGenre() { Id = 111, Name = "Christmas: Classical" },
                new MusicGenre() { Id = 112, Name = "Christmas: Jazz" },
                new MusicGenre() { Id = 113, Name = "Christmas: Modern" },
                new MusicGenre() { Id = 114, Name = "Christmas: Pop" },
                new MusicGenre() { Id = 115, Name = "Christmas: R&B" },
                new MusicGenre() { Id = 116, Name = "Christmas: Religious" },
                new MusicGenre() { Id = 117, Name = "Christmas: Rock" },
                new MusicGenre() { Id = 118, Name = "Easter" },
                new MusicGenre() { Id = 119, Name = "Halloween" },
                new MusicGenre() { Id = 120, Name = "Holiday: Other" },
                new MusicGenre() { Id = 121, Name = "Thanksgiving" },
                new MusicGenre() { Id = 122, Name = "Indie Pop" },
                new MusicGenre() { Id = 123, Name = "Industrial" },
                new MusicGenre() { Id = 124, Name = "Inspirational – Christian & Gospel" },
                new MusicGenre() { Id = 125, Name = "CCM" },
                new MusicGenre() { Id = 126, Name = "Christian Metal" },
                new MusicGenre() { Id = 127, Name = "Christian Pop" },
                new MusicGenre() { Id = 128, Name = "Christian Rap" },
                new MusicGenre() { Id = 129, Name = "Christian Rock" },
                new MusicGenre() { Id = 130, Name = "Classic Christian" },
                new MusicGenre() { Id = 131, Name = "Contemporary Gospel" },
                new MusicGenre() { Id = 132, Name = "Gospel" },
                new MusicGenre() { Id = 133, Name = "Christian & Gospel" },
                new MusicGenre() { Id = 134, Name = "Praise & Worship" },
                new MusicGenre() { Id = 135, Name = "Qawwali" },
                new MusicGenre() { Id = 136, Name = "Southern Gospel" },
                new MusicGenre() { Id = 137, Name = "Traditional Gospel" },
                new MusicGenre() { Id = 138, Name = "Instrumental" },
                new MusicGenre() { Id = 139, Name = "March (Marching Band)" },
                new MusicGenre() { Id = 140, Name = "J-Pop" },
                new MusicGenre() { Id = 141, Name = "J-Rock" },
                new MusicGenre() { Id = 142, Name = "J-Synth" },
                new MusicGenre() { Id = 143, Name = "J-Ska" },
                new MusicGenre() { Id = 144, Name = "J-Punk" },
                new MusicGenre() { Id = 145, Name = "Jazz" },
                new MusicGenre() { Id = 146, Name = "Acid Jazz" },
                new MusicGenre() { Id = 147, Name = "Avant-Garde Jazz" },
                new MusicGenre() { Id = 148, Name = "Big Band" },
                new MusicGenre() { Id = 149, Name = "Blue Note" },
                new MusicGenre() { Id = 150, Name = "Contemporary Jazz" },
                new MusicGenre() { Id = 151, Name = "Cool" },
                new MusicGenre() { Id = 152, Name = "Crossover Jazz" },
                new MusicGenre() { Id = 153, Name = "Dixieland" },
                new MusicGenre() { Id = 154, Name = "Ethio-jazz" },
                new MusicGenre() { Id = 155, Name = "Fusion" },
                new MusicGenre() { Id = 156, Name = "Hard Bop" },
                new MusicGenre() { Id = 157, Name = "Latin Jazz" },
                new MusicGenre() { Id = 158, Name = "Mainstream Jazz" },
                new MusicGenre() { Id = 159, Name = "Ragtime" },
                new MusicGenre() { Id = 160, Name = "Smooth Jazz" },
                new MusicGenre() { Id = 161, Name = "Trad Jazz" },
                new MusicGenre() { Id = 162, Name = "K-Pop" },
                new MusicGenre() { Id = 163, Name = "Karaoke" },
                new MusicGenre() { Id = 164, Name = "Kayokyoku" },
                new MusicGenre() { Id = 165, Name = "Latino" },
                new MusicGenre() { Id = 166, Name = "Alternativo & Rock Latino" },
                new MusicGenre() { Id = 167, Name = "Baladas y Boleros" },
                new MusicGenre() { Id = 168, Name = "Brazilian" },
                new MusicGenre() { Id = 169, Name = "Contemporary Latin" },
                new MusicGenre() { Id = 170, Name = "Latin Jazz" },
                new MusicGenre() { Id = 171, Name = "Pop Latino" },
                new MusicGenre() { Id = 172, Name = "Raíces" },
                new MusicGenre() { Id = 173, Name = "Reggaeton y Hip-Hop" },
                new MusicGenre() { Id = 174, Name = "Regional Mexicano" },
                new MusicGenre() { Id = 175, Name = "Salsa y Tropical" },
                new MusicGenre() { Id = 176, Name = "New Age" },
                new MusicGenre() { Id = 177, Name = "Environmental" },
                new MusicGenre() { Id = 178, Name = "Healing" },
                new MusicGenre() { Id = 179, Name = "Meditation" },
                new MusicGenre() { Id = 180, Name = "Nature" },
                new MusicGenre() { Id = 181, Name = "Relaxation" },
                new MusicGenre() { Id = 182, Name = "Travel" },
                new MusicGenre() { Id = 183, Name = "Opera" },
                new MusicGenre() { Id = 184, Name = "Pop" },
                new MusicGenre() { Id = 185, Name = "Adult Contemporary" },
                new MusicGenre() { Id = 186, Name = "Britpop" },
                new MusicGenre() { Id = 187, Name = "Pop/Rock" },
                new MusicGenre() { Id = 188, Name = "Soft Rock" },
                new MusicGenre() { Id = 189, Name = "Teen Pop" },
                new MusicGenre() { Id = 190, Name = "R&B/Soul" },
                new MusicGenre() { Id = 191, Name = "Contemporary R&B" },
                new MusicGenre() { Id = 192, Name = "Disco" },
                new MusicGenre() { Id = 193, Name = "Doo Wop" },
                new MusicGenre() { Id = 194, Name = "Funk" },
                new MusicGenre() { Id = 195, Name = "Motown" },
                new MusicGenre() { Id = 196, Name = "Neo-Soul" },
                new MusicGenre() { Id = 197, Name = "Quiet Storm" },
                new MusicGenre() { Id = 198, Name = "Soul" },
                new MusicGenre() { Id = 199, Name = "Reggae" },
                new MusicGenre() { Id = 200, Name = "Dancehall" },
                new MusicGenre() { Id = 201, Name = "Dub" },
                new MusicGenre() { Id = 202, Name = "Roots Reggae" },
                new MusicGenre() { Id = 203, Name = "Ska" },
                new MusicGenre() { Id = 204, Name = "Rock" },
                new MusicGenre() { Id = 205, Name = "Adult Alternative" },
                new MusicGenre() { Id = 206, Name = "American Trad Rock" },
                new MusicGenre() { Id = 207, Name = "Arena Rock" },
                new MusicGenre() { Id = 208, Name = "Blues-Rock" },
                new MusicGenre() { Id = 209, Name = "British Invasion" },
                new MusicGenre() { Id = 210, Name = "Death Metal/Black Metal" },
                new MusicGenre() { Id = 211, Name = "Glam Rock" },
                new MusicGenre() { Id = 212, Name = "Hair Metal" },
                new MusicGenre() { Id = 213, Name = "Hard Rock" },
                new MusicGenre() { Id = 214, Name = "Metal" },
                new MusicGenre() { Id = 215, Name = "Jam Bands" },
                new MusicGenre() { Id = 216, Name = "Prog-Rock/Art Rock" },
                new MusicGenre() { Id = 217, Name = "Psychedelic" },
                new MusicGenre() { Id = 218, Name = "Rock & Roll" },
                new MusicGenre() { Id = 219, Name = "Rockabilly" },
                new MusicGenre() { Id = 220, Name = "Roots Rock" },
                new MusicGenre() { Id = 221, Name = "Singer/Songwriter" },
                new MusicGenre() { Id = 222, Name = "Southern Rock" },
                new MusicGenre() { Id = 223, Name = "Surf" },
                new MusicGenre() { Id = 224, Name = "Tex-Mex" },
                new MusicGenre() { Id = 225, Name = "Singer/Songwriter" },
                new MusicGenre() { Id = 226, Name = "Alternative Folk" },
                new MusicGenre() { Id = 227, Name = "Contemporary Folk" },
                new MusicGenre() { Id = 228, Name = "Contemporary Singer/Songwriter" },
                new MusicGenre() { Id = 229, Name = "Folk-Rock" },
                new MusicGenre() { Id = 230, Name = "New Acoustic" },
                new MusicGenre() { Id = 231, Name = "Traditional Folk" },
                new MusicGenre() { Id = 232, Name = "Soundtrack" },
                new MusicGenre() { Id = 233, Name = "Foreign Cinema" },
                new MusicGenre() { Id = 234, Name = "Musicals" },
                new MusicGenre() { Id = 235, Name = "Original Score" },
                new MusicGenre() { Id = 236, Name = "Soundtrack" },
                new MusicGenre() { Id = 237, Name = "TV Soundtrack" },
                new MusicGenre() { Id = 238, Name = "Spoken Word" },
                new MusicGenre() { Id = 239, Name = "Tex-Mex / Tejano" },
                new MusicGenre() { Id = 240, Name = "Chicano" },
                new MusicGenre() { Id = 241, Name = "Classic" },
                new MusicGenre() { Id = 242, Name = "Conjunto" },
                new MusicGenre() { Id = 243, Name = "Conjunto Progressive" },
                new MusicGenre() { Id = 244, Name = "New Mex" },
                new MusicGenre() { Id = 245, Name = "Tex-Mex" },
                new MusicGenre() { Id = 246, Name = "Vocal" },
                new MusicGenre() { Id = 247, Name = "Barbershop" },
                new MusicGenre() { Id = 248, Name = "Doo-wop" },
                new MusicGenre() { Id = 249, Name = "Standards" },
                new MusicGenre() { Id = 250, Name = "Traditional Pop" },
                new MusicGenre() { Id = 251, Name = "Vocal Jazz" },
                new MusicGenre() { Id = 252, Name = "Vocal Pop" },
                new MusicGenre() { Id = 253, Name = "World" },
                new MusicGenre() { Id = 254, Name = "Africa" },
                new MusicGenre() { Id = 255, Name = "Afro-Beat" },
                new MusicGenre() { Id = 256, Name = "Afro-Pop" },
                new MusicGenre() { Id = 257, Name = "Asia" },
                new MusicGenre() { Id = 258, Name = "Australia" },
                new MusicGenre() { Id = 259, Name = "Bossa Nova" },
                new MusicGenre() { Id = 260, Name = "Cajun" },
                new MusicGenre() { Id = 261, Name = "Caribbean" },
                new MusicGenre() { Id = 262, Name = "Celtic" },
                new MusicGenre() { Id = 263, Name = "Celtic Folk" },
                new MusicGenre() { Id = 264, Name = "Contemporary Celtic" },
                new MusicGenre() { Id = 265, Name = "Drinking Songs" },
                new MusicGenre() { Id = 266, Name = "Drone" },
                new MusicGenre() { Id = 267, Name = "Europe" },
                new MusicGenre() { Id = 268, Name = "France" },
                new MusicGenre() { Id = 269, Name = "Hawaii" },
                new MusicGenre() { Id = 270, Name = "Indian Pop" },
                new MusicGenre() { Id = 271, Name = "Japan" },
                new MusicGenre() { Id = 272, Name = "Japanese Pop" },
                new MusicGenre() { Id = 273, Name = "Klezmer" },
                new MusicGenre() { Id = 274, Name = "Middle East" },
                new MusicGenre() { Id = 275, Name = "North America" },
                new MusicGenre() { Id = 276, Name = "Polka" },
                new MusicGenre() { Id = 277, Name = "South Africa" },
                new MusicGenre() { Id = 278, Name = "South America" },
                new MusicGenre() { Id = 279, Name = "Traditional Celtic" },
                new MusicGenre() { Id = 280, Name = "Worldbeat" },
                new MusicGenre() { Id = 281, Name = "Zydeco" }
            });

            await _dbContext.SaveChangesAsync(cancellationToken);

            _log.LogInformation("Seeded completed!");
        }
    }
}
